; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32s2]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
